# Generated by Django 5.1.3 on 2024-11-16 00:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaPeligro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "nivel_peligro",
                    models.IntegerField(
                        choices=[(1, "Bajo"), (2, "Medio"), (3, "Alto"), (4, "Mortal")],
                        default=1,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Raza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("habitat", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "inteligencia",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Criatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("tamano", models.CharField(max_length=100)),
                (
                    "categorias_peligro",
                    models.ManyToManyField(to="appHarryPotter.categoriapeligro"),
                ),
                (
                    "raza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appHarryPotter.raza",
                    ),
                ),
            ],
        ),
    ]
