# Generated by Django 5.1.3 on 2024-12-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHarryPotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criatura',
            name='categorias_peligro',
            field=models.ManyToManyField(blank=True, to='appHarryPotter.categoriapeligro'),
        ),
        migrations.AlterField(
            model_name='criatura',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
    ]
